# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-08 09:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtools', '0003_auto_20190608_0814'),
        ('profiles', '0002_profile_firebase_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firebase_qstn_id', models.TextField(default=None, null=True, verbose_name='Firebase question id')),
                ('firebase_cmnt_id', models.TextField(default=None, null=True, verbose_name='Firebase comment id')),
                ('start', models.DateTimeField(default=datetime.datetime(2019, 6, 8, 9, 35, 13, 905544))),
                ('end', models.DateTimeField(default=datetime.datetime(2019, 6, 8, 11, 35, 13, 905583))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
