# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-08 09:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 11, 46, 7, 959436)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 9, 46, 7, 959400)),
        ),
        migrations.AddField(
            model_name='lectureattendee',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Lecture'),
        ),
        migrations.AddField(
            model_name='lectureattendee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
