# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-08 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190608_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 11, 49, 7, 424363)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='firebase_cmnt_id',
            field=models.IntegerField(default=None, null=True, verbose_name='Firebase comment id'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='firebase_qstn_id',
            field=models.IntegerField(default=None, null=True, verbose_name='Firebase question id'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 9, 49, 7, 424323)),
        ),
    ]
