# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-08 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190608_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 11, 50, 54, 988745)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 9, 50, 54, 988705)),
        ),
    ]
