# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-08 12:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authtools', '0003_auto_20190608_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLecture',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firebase_qstn_id', models.IntegerField(default=None, null=True, verbose_name='Firebase question id')),
                ('firebase_cmnt_id', models.IntegerField(default=None, null=True, verbose_name='Firebase comment id')),
                ('start', models.DateTimeField(default=datetime.datetime(2019, 6, 8, 12, 47, 28, 463397))),
                ('end', models.DateTimeField(default=datetime.datetime(2019, 6, 8, 14, 47, 28, 463430))),
            ],
        ),
        migrations.CreateModel(
            name='BaseLectureAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Profile picture')),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verified')),
                ('firebase_chat_id', models.TextField(default=None, null=True, verbose_name='Firebase chat id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('baselecture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.BaseLecture')),
            ],
            bases=('profiles.baselecture',),
        ),
        migrations.CreateModel(
            name='LectureAttendee',
            fields=[
                ('baselectureattendee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.BaseLectureAttendee')),
            ],
            bases=('profiles.baselectureattendee',),
        ),
        migrations.AddField(
            model_name='baselectureattendee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baselectureattendee',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Lecture'),
        ),
    ]
